### ISSUE TITLE
Implement Tests

### ISSUE THREAD

**Issue by mishaalkandapath** [CSC207-2022F-UofT/course-project-flipwise-group-129#50]
Implement Tests for all use cases and entities and generate a test database

**Comment by kunzhi-yu** [comment]
Completed testing for UserLogin and UserRegister and it's associated controllers, presenters, etc.
Completed related documentation.

**Comment by mishaalkandapath** [comment]
All tests have been implemented, and work with some really good coverage. Well done everyone!
